config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  root to: 'landing#index'
  get :about, to: 'static_pages#about'

  post :upvote, to: 'votes#upvote'
  post :downvote, to: 'votes#downvote'

  resources :topics, except: [:show] do
    resources :posts, except: [:show] do
      resources :comments, except: [:show]


    end
  end
  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :edit, :create, :update]
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :votes, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :body, length: { minimum: 5 }, presence: true

  def total_votes
    votes.pluck(:value).sum
  end

  def total_upvote
    votes.where(value: 1).count
  end

  def total_downvote
    votes.where(value: -1).count
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :js
  before_action :authenticate!, only: [:create, :edit, :update, :new, :destroy]

  def index
    @topic = Topic.includes(:posts).friendly.find(params[:topic_id])
    @post = Post.friendly.find(params[:post_id])
    @comments = @post.comments.order(id: :ASC)
    @comment = Comment.new
  end

  # def new
  #   @topic = Topic.find_by(id: params[:topic_id])
  #   @post = Post.find_by(id: params[:post_id])
  # end

  def create
    @topic = Topic.friendly.find(params[:topic_id])
    @post = Post.friendly.find(params[:post_id])
    @comment = current_user.comments.build(comment_params.merge(post_id: @post.id))
    @new_comment = Comment.new

    if @comment.save
      CommentBroadcastJob.perform_later("create", @comment)
      flash.now[:success] = "Comment created"
    else
      flash.now[:danger] = @comment.errors.full_messages
    end
  end

  def edit
    @comment=Comment.find_by(id: params[:id])
    @post = Post.friendly.find(params[:post_id])
    @topic = Topic.friendly.find(params[:topic_id])
    authorize @comment
  end

  def update
    @topic = Topic.friendly.find(params[:topic_id])
    @post = Post.friendly.find(params[:post_id])
    @comment = Comment.find_by(id: params[:id])
    authorize @comment

    if @comment.update(comment_params)
      CommentBroadcastJob.perform_later("update", @comment)
      flash.now[:success] ="You've created a comment"
      # redirect_to topic_post_comments_path(@topic, @post)
    else
      flash.now[:danger] ="You've created a Dinesh"
      # redirect_to edit_topic_post_comment_path(@topic, @post)
    end

  end

  def destroy
    @topic = Topic.friendly.find(params[:topic_id])
    @post = Post.friendly.find(params[:post_id])
    @comment = Comment.find_by(id: params[:id])
    authorize @comment

    if @comment.destroy
      CommentBroadcastJob.perform_now("destroy", @comment)
      flash.now[:success] = "Delete batang hidung mu!"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :image)
  end

end

app/views/comments/_comment.html.erb
<div class="comment" data-id="<%= comment.id %>">
  <h1><%= comment.body %></h1>

  <div class = "votes">
    <h2>total votes</h2><%= comment.total_votes %>
    <h2>total upvote</h2><%= comment.total_upvote %>
    <h2>total downvote</h2><%= comment.total_downvote %>
  </div>

  <%= link_to "upvote", upvote_path(comment_id: comment.id),method: :post, remote: true %>
  <%= link_to "downvote", downvote_path(comment_id: comment.id),method: :post, remote: true %>

  <div class='control-panel'>
    <%= comment.user == current_user %>
    <% if comment.user ==  current_user || current_user&.admin? || current_user&.moderator? %>
    <%= link_to "Edit Comment", edit_topic_post_comment_path(post.topic, post, comment), remote: true %>
    <%= link_to "Delete", topic_post_comment_path(post.topic, post, comment), method: :delete, remote: true, data: { confirm: "Delete?" } %>
    <% end %>
  </div>
</div>

app/views/comments/_edit.html.erb
  <%= form_for(comment, url: topic_post_comment_path, remote: true, authenticity_token: true, html: { id: "comment-create-form", mutlipart: true }) do |f| %>
    <h1 class="text-center">
      Edit Comment
    </h1>

    <div class="form-body">
      <h4> <%= f.label :text_field, "Body" %> </h4>
      <%= f.text_field :body, id: "comment_body_field", class: 'form-control' %>
    </div>

    <div class="form-group text-center">
      <%= f.submit "Update Comment", class: "btn btn-primary btn-lg" %>
    </div>

    <div class="form-group">
      <h4 class="text-center"> Post Image </h4>
      <div id="preview-image">
        <% if @comment.image? %>
        <%= image_tag @comment.image, class: "img-settings img-responsive center-block" %>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
    </div>

  <% end %>

app/views/comments/_form.html.erb
<%= form_for(comment, url: topic_post_comments_path(post.topic, post),
    method: :post,remote: true, authenticity_token: true,
    html: { id: "comment-create-form", multipart: true }) do |f| %>

  <h1 class="text-center">
    Create comment
  </h1>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "comment_body_field",
    class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create comment", class: "btn btn-success btn-lg" %>
  </div>

  <div class="form-group">
    <h4 class="text-center"> Post Image </h4>
    <div id="preview-image">
      <% if comment.image? %>
        <%= image_tag comment.image,
        class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.file_field :image, id: "comment_image_field",
    class: 'form-control image-uploader' %>
  </div>
<% end %>

app/views/comments/_redit.html.erb
<div class="comments">
  <section class="background">
    <%= form_for(@comment, url: topic_post_comment_path, html: { id: "comment-create-form" }) do |f| %>
      <h1 class="text-center">
        Comment
      </h1>

      <div class="form-body">
        <h4> <%= f.label :text_field, "Body" %> </h4>
        <%= f.text_field :body, id: "comment_body_field", class: 'form-control' %>
      </div>

      <div class="form-group text-center">
        <%= f.submit "Update Comment", class: "btn btn-primary btn-lg" %>
      </div>

      <div class="form-group">
        <h4 class="text-center"> Post Image </h4>
        <div id="preview-image">
          <% if @comment.image? %>
          <%= image_tag @comment.image, class: "img-settings img-responsive center-block" %>
          <% end %>
        </div>
      </div>

      <div class="form-group">
        <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
      </div>

    <% end %>
  </section>
</div>

app/views/comments/create.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

<% if @comment.persisted? %>
  $('#comments-form-container').html("<%=j render partial: 'comments/form', locals: { comment: @new_comment, post: @post } %>")
<% end %>

app/views/comments/destroy.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

app/views/comments/edit.html.erb
<div class="comments">
  <section class="background">
    <%= form_for(@comment, url: topic_post_comment_path, html: { id: "comment-create-form" }) do |f| %>
      <h1 class="text-center">
        Comment
      </h1>

      <div class="form-body">
        <h4> <%= f.label :text_field, "Body" %> </h4>
        <%= f.text_field :body, id: "comment_body_field", class: 'form-control' %>
      </div>

      <div class="form-group text-center">
        <%= f.submit "Update Comment", class: "btn btn-primary btn-lg" %>
      </div>

      <div class="form-group">
        <h4 class="text-center"> Post Image </h4>
        <div id="preview-image">
          <% if @comment.image? %>
          <%= image_tag @comment.image, class: "img-settings img-responsive center-block" %>
          <% end %>
        </div>
      </div>

      <div class="form-group">
        <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
      </div>

    <% end %>
  </section>
</div>

app/views/comments/edit.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

$('.comment[data-id=<%=@comment.id%>]').html("<%=j render partial: 'comments/edit', locals: { comment: @comment, post: @comment.post } %>")

app/views/comments/index.html.erb
<div class="comments-index" data-id="<%= @post.id %>">


      <h1>Comments</h1>

      <div class="comments">
        <% @comments.each do |comment| %>
        <%= render partial: "comment", locals: { comment: comment, post: @post, extra_class: ""} %>
        <% end %>
      </div>

      <% if current_user%>
      <div id="comments-form-container">
        <%= render partial: "form", locals: { comment: @comment, post: @post} %>
      </div>
      <%end%>



</div>

app/views/comments/new.html.erb
<%= form_for(@comment, url: topic_post_comments_path(@topic, @post, @comment), html: { id: "comment-create-form" }) do |f| %>
  <h1 class="text-center">
    Create comment
  </h1>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "comment_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create comment", class: "btn btn-success btn-lg" %>
  </div>

  <div class="form-group">
    <h4 class="text-center"> Post Image </h4>
    <div id="preview-image">
      <% if @comment.image? %>
        <%= image_tag @comment.image, class: "img-settings img-responsive center-block" %>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.file_field :image, id: "comment_image_field", class: 'form-control image-uploader' %>
  </div>
<% end %>

app/views/comments/update.js.erb
$('#comment_<%=@comment.id%>').html("<%=j render partial: 'comments/comment', locals: { comment: @comment, post: @comment.post, topic: @topic } %>")