config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  root to: 'landing#index'
  get :about, to: 'static_pages#about'

  post :upvote, to: 'votes#upvote'
  post :downvote, to: 'votes#downvote'

  resources :topics, except: [:show] do
    resources :posts, except: [:show] do
      resources :comments, except: [:show]


    end
  end
  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :edit, :create, :update]
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/partials/_flash_messages.html.erb
<div id="flash-messages-container">
<% flash.each do |k,v| %>
  <section class="flash-messages">
    <div class="alert alert-<%=k%>">
      <button type="button" class="close" data-dismiss="alert" id= "close">
        &times;
      </button>
      <div class="message">
        <%= display_message(v) %>
      </div>
    </div>
  </section>
<% end %>
</div>

app/views/partials/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Two Wheel Trouble", root_path, class: "navbar-brand" %>

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-dropdown" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="header-dropdown">
      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "About Us", about_path %></li>
        <li><%= link_to "Topics", topics_path %></li>
        <% if current_user %>
        <li>
          <%= link_to "My Account", '#', class: 'user-account', data: { toggle: "modal", target: "#account"}%>
        </li>

        <li>
          <%= link_to "Logout", session_path(current_user), method: :delete, class: 'white shadowed link-styling' %>
        </li>

        <% else %>

        <li>
          <%= link_to "Register", '#', class: 'user-register', data: { toggle: "modal", target: "#register"}%>
        </li>

        <li>
          <%= link_to "Login", '#', class: 'user-login', data: { toggle: "modal", target: "#login" } %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>