config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  root to: 'landing#index'
  get :about, to: 'static_pages#about'

  post :upvote, to: 'votes#upvote'
  post :downvote, to: 'votes#downvote'

  resources :topics, except: [:show] do
    resources :posts, except: [:show] do
      resources :comments, except: [:show]


    end
  end
  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :edit, :create, :update]
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :topics
  has_many :posts
  has_many :comments
  has_many :votes
  mount_uploader :image, ImageUploader
  enum role: [:user, :moderator, :admin]
  extend FriendlyId
  friendly_id :username

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        flash[:success]="New User created"
        redirect_to root_path
      else
        flash[:danger]= "Passwords do not match!"
        redirect_to root_path
      end
  end

  def update
    @user = User.friendly.find(params[:id])
    if @user.update(user_params)
      flash[:success]="Account Updated"
      redirect_to root_path
    else
      redirect_to edit_user_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :username, :image)
    end

end

app/views/users/_edit.html.erb
<div class = "modal fade users" id = "account">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">

        <section class = "background">

          <%= form_for(current_user, url: user_path(current_user), html: { id: "user-create-form" }) do |f| %>
          <div class="form-group">
            <h4 class="text-center"> Profile Picture </h4>
            <div id="preview-image">

              <%= image_tag "", class: "img-settings img-responsive center-block" %>

            </div>
          </div>

          <div class="form-group">
            <%= f.file_field :image, id: "user_image_field", class: 'form-control image-uploader' %>
          </div>

          <h1 class="text-center">
            User Account
          </h1>

          <div class="form-group">
            <h4> <%= f.label :username_field, "Username" %> </h4>
            <%= f.text_field :username, required: true, id: "username_field", class: 'form-control' %>
          </div>

          <div class="form-group">
            <h4> <%= f.label :email_field, "Email" %> </h4>
            <%= f.text_field :email, id: "email_field", class: 'form-control' %>
          </div>

          <div class="form-group">
            <h4> <%= f.label :password_field, "Password" %> </h4>
            <%= f.password_field :password, id: "password_field", class: 'form-control' %>

            <h4> <%= f.label :password_field, "Password Confirmation" %> </h4>
            <%= f.password_field :password_confirmation, id: "password_confirmation_field", class: 'form-control' %>
          </div>

          <div class="form-group text-center">
            <%= f.submit "Update Account", class: "btn btn-success btn-lg" %>
          </div>
          <% end %>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/users/_register.html.erb
<div class = "modal fade user" id="register">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <section class="background">
          <%= form_for(:user, url: users_path, html: { id: "user-create-form" }) do |f| %>
          <div class="form-group">
            <h4 class="text-center"> Profile Picture </h4>
            <div id="preview-image">

              <%= image_tag "", class: "img-settings img-responsive center-block" %>

            </div>
          </div>

          <div class="form-group">
            <%= f.file_field :image, id: "user_image_field", class: 'form-control image-uploader' %>
          </div>

          <h1 class="text-center">
            New User Login
          </h1>

          <div class="form-group">
            <h4> <%= f.label :username_field, "Username" %> </h4>
            <%= f.text_field :username, required: true, id: "username_field", class: 'form-control' %>
          </div>

          <div class="form-group">
            <h4> <%= f.label :email_field, "Email" %> </h4>
            <%= f.text_field :email, id: "email_field", class: 'form-control' %>
          </div>

          <div class="form-group">
            <h4> <%= f.label :password_field, "Password" %> </h4>
            <%= f.password_field :password, id: "password_field", class: 'form-control' %>

            <h4> <%= f.label :password_field, "Password Confirmation" %> </h4>
            <%= f.password_field :password_confirmation, id: "password_confirmation_field", class: 'form-control' %>
          </div>

          <div class="form-group text-center">
            <%= f.submit "Create Login", class: "btn btn-success btn-lg" %>
          </div>
          <% end %>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class = "users">
  <section class = "background">
    <%= form_for(@user, url: user_path(@user), html: { id: "user-create-form" }) do |f| %>
      <div class="form-group">
        <h4 class="text-center"> Profile Picture </h4>
          <div id="preview-image">
            <% if @user.image? %>
            <%= image_tag @user.image, class: "img-settings img-responsive center-block" %>
            <% end %>
          </div>
      </div>

      <div class="form-group">
        <%= f.file_field :image, id: "user_image_field", class: 'form-control image-uploader' %>
      </div>

      <h1 class="text-center">
        User Account
      </h1>

      <div class="form-group">
        <h4> <%= f.label :username_field, "Username" %> </h4>
        <%= f.text_field :username, required: true, id: "username_field", class: 'form-control' %>
      </div>

      <div class="form-group">
        <h4> <%= f.label :email_field, "Email" %> </h4>
        <%= f.text_field :email, id: "email_field", class: 'form-control' %>
      </div>

      <div class="form-group">
        <h4> <%= f.label :password_field, "Password" %> </h4>
        <%= f.password_field :password, id: "password_field", class: 'form-control' %>

        <h4> <%= f.label :password_field, "Password Confirmation" %> </h4>
         <%= f.password_field :password_confirmation, id: "password_confirmation_field", class: 'form-control' %>
      </div>

      <div class="form-group text-center">
        <%= f.submit "Update Account", class: "btn btn-success btn-lg" %>
      </div>
    <% end %>
  </section>
</div>

app/views/users/index.html.erb
<div class="users">
  <section class="background">
    <%= form_for(@user, url: users_path, html: { id: "user-create-form" }) do |f| %>
      <h1 class="text-center">
       New User Login
      </h1>

      <div class="form-group">
        <h4> <%= f.label :email_field, "Email" %> </h4>
        <%= f.text_field :email, required: true, id: "email_field", class: 'form-control' %>
      </div>

      <div class="form-group">
        <h4> <%= f.label :password_field, "Password" %> </h4>
        <%= f.text_field :password, id: "password_field", class: 'form-control' %>
      </div>

      <div class="form-group text-center">
        <%= f.submit "Login", class: "btn btn-success btn-lg" %>
      </div>

      <div class="form-group text-center">
        <li><%= link_to "New User", new_user_path %></li>
      </div>
    <% end %>
  </section>
</div>  

app/views/users/new.html.erb
<div class = "users">
  <section class="background">
    <%= form_for(@user, url: users_path, html: { id: "user-create-form" }) do |f| %>
      <div class="form-group">
        <h4 class="text-center"> Profile Picture </h4>
          <div id="preview-image">
            <% if @user.image? %>
            <%= image_tag @user.image, class: "img-settings img-responsive center-block" %>
            <% end %>
          </div>
      </div>

      <div class="form-group">
        <%= f.file_field :image, id: "user_image_field", class: 'form-control image-uploader' %>
      </div>

      <h1 class="text-center">
       New User Login
      </h1>

      <div class="form-group">
        <h4> <%= f.label :username_field, "Username" %> </h4>
        <%= f.text_field :username, required: true, id: "username_field", class: 'form-control' %>
      </div>

      <div class="form-group">
        <h4> <%= f.label :email_field, "Email" %> </h4>
        <%= f.text_field :email, id: "email_field", class: 'form-control' %>
      </div>

      <div class="form-group">
        <h4> <%= f.label :password_field, "Password" %> </h4>
        <%= f.password_field :password, id: "password_field", class: 'form-control' %>

        <h4> <%= f.label :password_field, "Password Confirmation" %> </h4>
         <%= f.password_field :password_confirmation, id: "password_confirmation_field", class: 'form-control' %>
      </div>

      <div class="form-group text-center">
        <%= f.submit "Create Login", class: "btn btn-success btn-lg" %>
      </div>
    <% end %>
  </section>
</div>