config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  root to: 'landing#index'
  get :about, to: 'static_pages#about'

  post :upvote, to: 'votes#upvote'
  post :downvote, to: 'votes#downvote'

  resources :topics, except: [:show] do
    resources :posts, except: [:show] do
      resources :comments, except: [:show]


    end
  end
  resources :users, only: [:new, :edit, :create, :update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :edit, :create, :update]
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :comments, dependent: :destroy
   belongs_to :topic
   belongs_to :user
   mount_uploader :image, ImageUploader
   validates :title, length: { minimum: 5 }, presence: true
   validates :body, length: { minimum: 5 }, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :js
  before_action :authenticate!, only: [:create, :edit, :update, :new, :destroy]
  def index
    @topic = Topic.includes(:posts).friendly.find(params[:topic_id])
    @posts = @topic.posts.order(id: :ASC)
    @post = Post.new
  end

  def create
    @topic = Topic.friendly.find(params[:topic_id])
    @post = current_user.posts.build(post_params.merge(topic_id: @topic.id))
    @new_post = Post.new

    if @post.save
      flash[:success] = "You've created a new post."
    else
      flash[:danger] = @post.errors.full_messages
    end
  end

  def edit
    @post = Post.friendly.find(params[:id])
    @topic = @post.topic
    authorize @post
  end

  def update
    @topic = Topic.friendly.find(params[:topic_id])
    @post = Post.friendly.find(params[:id])
    authorize @post

    if @post.update(post_params)
      flash.now[:success] = "Post updated"
      # redirect_to topic_posts_path(@topic)
    else
      flash.now[:danger] = "You created a Dinesh"
      # redirect_to edit_topic_post_path(@topic, @post)
    end
  end

  def destroy
    @post = Post.friendly.find(params[:id])
    @topic = @post.topic
    authorize @post

    if @post.destroy
      flash.now[:success] = "Post suda tada"
      # redirect_to topic_posts_path(@topic)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/views/posts/_edit.html.erb
<%= form_for(post, url: topic_post_path,remote: true, html: { id: "post-create-form", multipart: true }) do |f| %>
  <h1 class="text-center">
    Edit Post
  </h1>

  <div class="form-title">
    <h4> <%= f.label :title_field, "Title"%> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-body">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Update post", class: "btn btn-primary btn-lg" %>
  </div>

  <div class="form-group">
    <h4 class="text-center"> Post Image </h4>
  <div id="preview-image">
    <% if @post.image? %>
    <%= image_tag @post.image, class: "img-settings img-responsive center-block" %>
    <% end %>
  </div>
</div>

<div class="form-group">
  <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
</div>
  <% end %>

app/views/posts/_form.html.erb
<%= form_for(post, url: topic_posts_path(topic, post),method: :post,remote: true,authenticity_token: true, html: { id: "post-create-form" ,multipart: true}) do |f| %>

  <h1 class="text-center">
    Create post
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create post", class: "btn btn-success btn-lg" %>
  </div>

  <div class="form-group">
    <h4 class="text-center"> Post Image </h4>
      <div id="preview-image">
        <% if post.image? %>
        <%= image_tag post.image, class: "img-settings img-responsive center-block" %>
        <% end %>
      </div>
  </div>

  <div class="form-group">
    <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<div id="post_<%=post.id%>">
  <div class="post_child">

    <h3><%= link_to post.title, topic_post_comments_path(topic,post) %></h3>
    <h5><%= post.body %></h5>
    <%= image_tag post.image %>
    <%= link_to "Edit Post", edit_topic_post_path(topic, post),remote: true %>
    <%= link_to "Delete", topic_post_path(topic, post), method: :delete,remote: true, data: { confirm: "Delete?" } %>

  </div>
</div>

app/views/posts/create.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")

<% if @post.persisted? %>
  $('#posts').append("<%=j render partial: 'posts/post', locals: { topic: @topic, post: @post } %>")
  $('#posts-form-container').html("<%=j render partial: 'posts/form', locals: { topic: @topic, post: @new_post } %>")
<% end %>

app/views/posts/destroy.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")
  <% if @post.destroyed? %>
    $("#post_<%= @post.id %>").remove()
  <%end%>

app/views/posts/edit.js.erb
$('#flash-messages-container').html("<%=j render partial: 'partials/flash_messages' %>")
$('#post_<%=@post.id%>').html("<%=j render partial: 'posts/edit', locals: { topic: @topic, post: @post } %>")

app/views/posts/index.html.erb
<div class="posts">
  <h1>Posts</h1>
  <section class="background">
    <section class="post-container">
      <div class="post_parent">
          <div id= "posts">
            <% @posts.each do |post| %>
              <%= render partial: "post", locals: {topic: @topic, post: post}%>
            <%end%>
        </div>
      </div>
    </section>

    <section class="forms-container">
      <div class="post-form">
        <div id="posts-form-container">
          <%= render partial: "form", locals: {topic: @topic, post: @post}%>
        </div>
      </div>
    </section>

  </section>
</div>

app/views/posts/new.html.erb
<%= form_for(@post, url: topic_posts_path, html: { id: "post-create-form" }) do |f| %>
  <h1 class="text-center">
    Create post
  </h1>

  <div class="form-group">
    <h4> <%= f.label :title_field, "Title" %> </h4>
    <%= f.text_field :title, required: true, id: "post_title_field", class: 'form-control' %>
  </div>

  <div class="form-group">
    <h4> <%= f.label :text_field, "Body" %> </h4>
    <%= f.text_field :body, id: "post_body_field", class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Create post", class: "btn btn-success btn-lg" %>
  </div>

  <div class="form-group">
    <h4 class="text-center"> Post Image </h4>
      <div id="preview-image">
        <% if @post.image? %>
        <%= image_tag @post.image, class: "img-settings img-responsive center-block" %>
        <% end %>
      </div>
  </div>

  <div class="form-group">
    <%= f.file_field :image, id: "post_image_field", class: 'form-control image-uploader' %>
  </div>

<% end %>

app/views/posts/show.html.erb
<h1><%= @posts.title %></h1>
<p><%= @posts.body %></p>
  <%= link_to "Delete", post_path(@posts), method: :delete, data: { confirm: "Delete?" } %>

app/views/posts/update.js.erb
$('#post_<%=@post.id%>').html("<%=j render partial: 'posts/post', locals: { topic: @topic, post: @post } %>")